CREATE DATABASE DB_CURSO_DA_MINHA_VIDA;

USE DB_CURSO_DA_MINHA_VIDA;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT(5) AUTO_INCREMENT,
TEMA VARCHAR(50), 
NIVEL VARCHAR(50),
PRIMARY KEY (ID)
);

CREATE TABLE TB_CURSOS(
ID BIGINT(5) AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
VALOR DECIMAL(5,2) NOT NULL,
CARGA_HORARIA INT(5) NOT NULL,
CRIADOR VARCHAR(50) NOT NULL,
CATEGORIAS_ID BIGINT,
PRIMARY KEY(ID),
FOREIGN KEY (CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID) 
);

INSERT INTO TB_CATEGORIAS(TEMA,NIVEL) VALUES ("SOFTWARE","BÁSICO");
INSERT INTO TB_CATEGORIAS(TEMA,NIVEL) VALUES ("SOFTWARE","INTERMEDIÁRIO");
INSERT INTO TB_CATEGORIAS(TEMA,NIVEL) VALUES ("SOFTWARE","AVANÇADO");
INSERT INTO TB_CATEGORIAS(TEMA,NIVEL) VALUES ("HARDWARE","BÁSICO");
INSERT INTO TB_CATEGORIAS(TEMA,NIVEL) VALUES ("HARDWARE","INTERMEDIÁRIO");
INSERT INTO TB_CATEGORIAS(TEMA,NIVEL) VALUES ("HARDWARE","AVANÇADO");

SELECT * FROM TB_CATEGORIAS;

INSERT INTO TB_CURSOS(NOME,VALOR,CARGA_HORARIA,CRIADOR,CATEGORIAS_ID) VALUES ("JAVA POO",700.00,460,"BRIOLLI",3);
INSERT INTO TB_CURSOS(NOME,VALOR,CARGA_HORARIA,CRIADOR,CATEGORIAS_ID) VALUES ("CONSERTO DISPLAY",650.00,100,"KEVVI",5);
INSERT INTO TB_CURSOS(NOME,VALOR,CARGA_HORARIA,CRIADOR,CATEGORIAS_ID) VALUES ("GIT HUB",250.00,50,"OZZY",1);
INSERT INTO TB_CURSOS(NOME,VALOR,CARGA_HORARIA,CRIADOR,CATEGORIAS_ID) VALUES ("CONSERTO CPU",900.00,10,"KAUTZ",4);
INSERT INTO TB_CURSOS(NOME,VALOR,CARGA_HORARIA,CRIADOR,CATEGORIAS_ID) VALUES ("LAÇO CONDICIONAL",510.00,260,"TOURS",2);
INSERT INTO TB_CURSOS(NOME,VALOR,CARGA_HORARIA,CRIADOR,CATEGORIAS_ID) VALUES ("CONSERTO MOUSE E TECLADO ",150.00,45,"CHAUN",6);
INSERT INTO TB_CURSOS(NOME,VALOR,CARGA_HORARIA,CRIADOR,CATEGORIAS_ID) VALUES ("DESCOBRINDO JAVA",845.00,300,"LAXI",1);
INSERT INTO TB_CURSOS(NOME,VALOR,CARGA_HORARIA,CRIADOR,CATEGORIAS_ID) VALUES ("ELETRICA",430.00,600,"KAUTE",6);

SELECT * FROM TB_CURSOS;

SELECT NOME,VALOR,CARGA_HORARIA,CRIADOR FROM TB_CURSOS WHERE VALOR > 500.00;

SELECT NOME,VALOR,CARGA_HORARIA,CRIADOR FROM TB_CURSOS WHERE VALOR > 600.00 AND VALOR < 1000.00;

SELECT  NOME,VALOR,CARGA_HORARIA,CRIADOR FROM TB_CURSOS WHERE NOME LIKE "%J%";

SELECT * FROM TB_CURSOS INNER JOIN TB_CATEGORIAS ON
TB_CURSOS.CATEGORIAS_ID = TB_CATEGORIAS.ID;

SELECT * FROM TB_CURSOS INNER JOIN TB_CATEGORIAS ON
TB_CURSOS.CATEGORIAS_ID = TB_CATEGORIAS.ID WHERE TEMA = "SOFTWARE";