CREATE DATABASE DB_FARMACIA_BEM_ESTAR;

USE DB_FARMACIA_BEM_ESTAR;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT(5) AUTO_INCREMENT,
COSMETICO VARCHAR(50), 
REMEDIO VARCHAR(50),
PRIMARY KEY (ID)
);

CREATE TABLE TB_PRODUTOS(
ID BIGINT(5) AUTO_INCREMENT,
PRODUTO VARCHAR(50) NOT NULL,
VALOR DECIMAL(5,2) NOT NULL,
CAIXA_ATENDIMENTO INT NOT NULL,
ATENDENTE VARCHAR(50) NOT NULL,
CATEGORIAS_ID BIGINT,
PRIMARY KEY(ID),
FOREIGN KEY (CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID) 
);

INSERT INTO TB_CATEGORIAS(COSMETICO,REMEDIO) VALUES ("MAQUIAGEM","");
INSERT INTO TB_CATEGORIAS(COSMETICO,REMEDIO) VALUES ("SKIN CARE","");
INSERT INTO TB_CATEGORIAS(COSMETICO,REMEDIO) VALUES ("","CAPSULAS");
INSERT INTO TB_CATEGORIAS(COSMETICO,REMEDIO) VALUES ("","POMADAS");
INSERT INTO TB_CATEGORIAS(COSMETICO,REMEDIO) VALUES ("","GOTAS");

SELECT * FROM TB_CATEGORIAS;

INSERT INTO TB_PRODUTOS(PRODUTO,VALOR,CAIXA_ATENDIMENTO,ATENDENTE,CATEGORIAS_ID) VALUES ("ÁGUA MICELAR",30.00,5,"JUVIA",2);
INSERT INTO TB_PRODUTOS(PRODUTO,VALOR,CAIXA_ATENDIMENTO,ATENDENTE,CATEGORIAS_ID) VALUES ("BATOM",20.00,3,"NATSU",1);
INSERT INTO TB_PRODUTOS(PRODUTO,VALOR,CAIXA_ATENDIMENTO,ATENDENTE,CATEGORIAS_ID) VALUES ("MICOSIL",65.00,9,"GRAY",4);
INSERT INTO TB_PRODUTOS(PRODUTO,VALOR,CAIXA_ATENDIMENTO,ATENDENTE,CATEGORIAS_ID) VALUES ("DIPIRONA",70.00,7,"MIYA",5);
INSERT INTO TB_PRODUTOS(PRODUTO,VALOR,CAIXA_ATENDIMENTO,ATENDENTE,CATEGORIAS_ID) VALUES ("GRIPOL",51.00,4,"GAJEEL",3);
INSERT INTO TB_PRODUTOS(PRODUTO,VALOR,CAIXA_ATENDIMENTO,ATENDENTE,CATEGORIAS_ID) VALUES ("PROTETOR SOLAR",99.00,1,"LISANNA",2);
INSERT INTO TB_PRODUTOS(PRODUTO,VALOR,CAIXA_ATENDIMENTO,ATENDENTE,CATEGORIAS_ID) VALUES ("CRAVIL",45.00,1,"CASTIEL",4);
INSERT INTO TB_PRODUTOS(PRODUTO,VALOR,CAIXA_ATENDIMENTO,ATENDENTE,CATEGORIAS_ID) VALUES ("OMEPRAZOL",75.00,10,"LEVY",3);

SELECT * FROM TB_PRODUTOS;

SELECT PRODUTO,VALOR,CAIXA_ATENDIMENTO,ATENDENTE FROM TB_PRODUTOS WHERE VALOR > 50.00;

SELECT PRODUTO,VALOR,CAIXA_ATENDIMENTO,ATENDENTE FROM TB_PRODUTOS WHERE VALOR > 5.00 AND VALOR < 60.00;

SELECT PRODUTO,VALOR,CAIXA_ATENDIMENTO,ATENDENTE FROM TB_PRODUTOS WHERE PRODUTO LIKE "%C%";

SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON
TB_PRODUTOS.CATEGORIAS_ID = TB_CATEGORIAS.ID;

SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON
TB_PRODUTOS.CATEGORIAS_ID = TB_CATEGORIAS.ID WHERE COSMETICO = "SKIN CARE";