CREATE DATABASE DB_GENERATION_GAME_ONLINE;

USE DB_GENERATION_GAME_ONLINE;

CREATE TABLE TB_CLASSES(
ID BIGINT(5) AUTO_INCREMENT,
CLASSE VARCHAR (100) NOT NULL,
LANE VARCHAR(100) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE TB_PERSONAGENS(
ID BIGINT(5) AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
HABILIDADE VARCHAR(50) NOT NULL,
DEFESA INT(4) NOT NULL,
ATAQUE INT(4) NOT NULL,
CLASSES_ID BIGINT, 
PRIMARY KEY(ID),
FOREIGN KEY (CLASSES_ID) REFERENCES TB_CLASSES(ID)
);

INSERT INTO TB_CLASSES(CLASSE,LANE)
 VALUES("MAGO","MID");
INSERT INTO TB_CLASSES(CLASSE,LANE)
 VALUES("SOLDADO","JUNGLE");
 INSERT INTO TB_CLASSES(CLASSE,LANE)
 VALUES("ATIRADOR","BOT LANE");
 INSERT INTO TB_CLASSES(CLASSE,LANE)
 VALUES("SUPORTE","ROTACIONAR");
 INSERT INTO TB_CLASSES(CLASSE,LANE)
 VALUES("TANK","ROTACIONAR");
 
 SELECT * FROM TB_CLASSES;
 
INSERT INTO TB_PERSONAGENS(NOME,HABILIDADE,DEFESA,ATAQUE,CLASSES_ID)
VALUES("KAGURA","GUARDA-CHUVA",1500,2000,1);
INSERT INTO TB_PERSONAGENS(NOME,HABILIDADE,DEFESA,ATAQUE,CLASSES_ID)
VALUES("SUN","CLONES",2500,2500,2);
INSERT INTO TB_PERSONAGENS(NOME,HABILIDADE,DEFESA,ATAQUE,CLASSES_ID)
VALUES("HYLOS","PARALISAR",500,1000,5);
INSERT INTO TB_PERSONAGENS(NOME,HABILIDADE,DEFESA,ATAQUE,CLASSES_ID)
VALUES("CYCLOPS","BOLHAS",1900,2500,1);
INSERT INTO TB_PERSONAGENS(NOME,HABILIDADE,DEFESA,ATAQUE,CLASSES_ID)
VALUES("CLINT","ESPINGARDA",3000,5000,3);
INSERT INTO TB_PERSONAGENS(NOME,HABILIDADE,DEFESA,ATAQUE,CLASSES_ID)
VALUES("RAFAELA","CURAR",800,600,4);
INSERT INTO TB_PERSONAGENS(NOME,HABILIDADE,DEFESA,ATAQUE,CLASSES_ID)
VALUES("BALMOND","GIRAR",2500,2);
INSERT INTO TB_PERSONAGENS(NOME,HABILIDADE,DEFESA,ATAQUE,CLASSES_ID)
VALUES("ZILONG","ESPADA",200,500,2);

SELECT * FROM TB_PERSONAGENS;

SELECT * FROM TB_PERSONAGENS WHERE DEFESA BETWEEN 1000 AND 2000;

SELECT * FROM TB_PERSONAGENS WHERE ATAQUE > 2000;

SELECT * FROM TB_PERSONAGENS WHERE NOME LIKE "%C%";

SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON
TB_PERSONAGENS.CLASSES_ID = TB_CLASSES.ID;

SELECT * FROM TB_PERSONAGENS
INNER JOIN TB_CLASSES ON TB_PERSONAGENS.CLASSES_ID = TB_CLASSES.ID WHERE CLASSE = "MAGO";

