CREATE DATABASE DB_PIZZARIA_LEGAL;

USE DB_PIZZARIA_LEGAL;

CREATE TABLE TB_CATEGORIA(
ID BIGINT(5) AUTO_INCREMENT,
SABOR_PALADAR VARCHAR(50) NOT NULL, 
TAMANHO VARCHAR(50) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE TB_PIZZAS(
ID BIGINT(5) AUTO_INCREMENT,
CLIENTE VARCHAR(50) NOT NULL,
SABOR VARCHAR(50) NOT NULL,
VALOR DECIMAL(4,2) NOT NULL,
BORDA_RECHEADA BOOLEAN NOT NULL,
CATEGORIA_ID BIGINT,
PRIMARY KEY(ID),
FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIA(ID) 
);

INSERT INTO TB_CATEGORIA(SABOR_PALADAR,TAMANHO) VALUES ("SALGADO","PEQUENO");
INSERT INTO TB_CATEGORIA(SABOR_PALADAR,TAMANHO) VALUES ("SALGADO","MÉDIO");
INSERT INTO TB_CATEGORIA(SABOR_PALADAR,TAMANHO) VALUES ("SALGADO","GRANDE");
INSERT INTO TB_CATEGORIA(SABOR_PALADAR,TAMANHO) VALUES ("DOCE","PEQUENO");
INSERT INTO TB_CATEGORIA(SABOR_PALADAR,TAMANHO) VALUES ("DOCE","MÉDIO");
INSERT INTO TB_CATEGORIA(SABOR_PALADAR,TAMANHO) VALUES ("DOCE","GRANDE");

SELECT * FROM TB_CATEGORIA;

INSERT INTO TB_PIZZAS(CLIENTE,SABOR,VALOR,BORDA_RECHEADA,CATEGORIA_ID) VALUES ("THOR","CALABRESA",46.00,1,3);
INSERT INTO TB_PIZZAS(CLIENTE,SABOR,VALOR,BORDA_RECHEADA,CATEGORIA_ID) VALUES ("SPYKE","CHOCOLATE",45.00,0,5);
INSERT INTO TB_PIZZAS(CLIENTE,SABOR,VALOR,BORDA_RECHEADA,CATEGORIA_ID) VALUES ("LAYLA","FRANGO",60.00,1,1);
INSERT INTO TB_PIZZAS(CLIENTE,SABOR,VALOR,BORDA_RECHEADA,CATEGORIA_ID) VALUES ("CHEVYA","MORANGO",90.00,0,6);
INSERT INTO TB_PIZZAS(CLIENTE,SABOR,VALOR,BORDA_RECHEADA,CATEGORIA_ID) VALUES ("MAICÃO","ATUM",55.00,0,2);
INSERT INTO TB_PIZZAS(CLIENTE,SABOR,VALOR,BORDA_RECHEADA,CATEGORIA_ID) VALUES ("TOTÓ","PRESTIGIO",99.00,1,4);
INSERT INTO TB_PIZZAS(CLIENTE,SABOR,VALOR,BORDA_RECHEADA,CATEGORIA_ID) VALUES ("FANNY","QUEIJO",40.00,1,3);
INSERT INTO TB_PIZZAS(CLIENTE,SABOR,VALOR,BORDA_RECHEADA,CATEGORIA_ID) VALUES ("INDIGO","GOIABA",50.00,0,5);

SELECT * FROM TB_PIZZAS;

SELECT * FROM TB_PIZZAS WHERE VALOR > 45.00;

SELECT * FROM TB_PIZZAS WHERE VALOR > 50.00 AND VALOR < 100.00;

SELECT * FROM TB_PIZZAS WHERE SABOR LIKE "%M%";

SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIA ON
TB_PIZZAS.CATEGORIA_ID = TB_CATEGORIA.ID;

SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIA ON
TB_PIZZAS.CATEGORIA_ID = TB_CATEGORIA.ID WHERE SABOR_PALADAR = "DOCE";