CREATE DATABASE RH_EMPRESA;

USE RH_EMPRESA;

CREATE TABLE RH_FUNCIONARIOS( 
ID BIGINT (5) AUTO_INCREMENT,
NOME VARCHAR (50) NOT NULL,
IDADE INT(2),
FUNCAO VARCHAR(30),
SALARIO DECIMAL(10),
ATIVO BOOLEAN,
PRIMARY KEY (ID)
);

INSERT INTO RH_FUNCIONARIOS(NOME,IDADE,FUNCAO,SALARIO,ATIVO) 
VALUES ("Antonia Hill",35,"Administradora",3500,TRUE);
INSERT INTO RH_FUNCIONARIOS(NOME,IDADE,FUNCAO,SALARIO,ATIVO) 
VALUES ("Bianca Berg",27,"Recepcionista",2300,FALSE);
INSERT INTO RH_FUNCIONARIOS(NOME,IDADE,FUNCAO,SALARIO,ATIVO)
VALUES ("Catarina Earl", 31,"Gerente", 5500,TRUE);
INSERT INTO RH_FUNCIONARIOS(NOME,IDADE,FUNCAO,SALARIO,ATIVO)
VALUES ("Diego Santis", 45,"Supervisor", 4750,TRUE);
INSERT INTO RH_FUNCIONARIOS(NOME,IDADE,FUNCAO,SALARIO,ATIVO)
VALUES ("Martina Silva", 20,"Desenvolvedora Software", 4000,FALSE);

SELECT * FROM RH_FUNCIONARIOS WHERE SALARIO < 2000;

SELECT * FROM RH_FUNCIONARIOS WHERE SALARIO > 2000;

SELECT * FROM RH_FUNCIONARIOS;




